import './index.scss'
const LeftPanel = ()=>{
  return(
    <div className="left-pane-container">
      <ul className="list-container">
        <li>发现音乐</li>
        <li>视频</li>
        <li>朋友</li>
        <li>直播</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
        <li>私人FM</li>
      </ul>
    </div>
  )
}

export default LeftPanel